name: Collaborative Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Code Formatting
        run: |
          echo "Checking code format..."
          black --check main_project.py || exit 1

      - name: Run Tests
        run: |
          echo "Running tests..."
          pytest || exit 1
