name: Collaborative Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sync-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Changes
        run: |
          echo "Changes have been pushed or a pull request has been created. Collaborators should review."
